daemonset:
  enabled: true
  port: 9090
  image:
#    repository: docker.io/appdynamics/machine-agent-analytics
    repository: docker.io/mhkadam/machine-agent-analytics
    tag: 21.3.0
    pullPolicy: Always
  nodeSelector: {}
  tolerations: {}
  podSecurityContext:
    privileged: false
  priorityClassName: ""
  resources:
    limits:
      cpu: 600m
      memory: "2G"
    requests: 
      cpu: 300m
      memory: "1G"
  netvizResources:
    limits:
      cpu: 200m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 150Mi
  envFromConfigMap:
  - ma-config
  envValueFromConfigMap: {}
  envValueFrom:
    APPDYNAMICS_AGENT_NODE_NAME:
      fieldRef:
        fieldPath: spec.nodeName

controller:
  host: ps-east-prod.saas.appdynamics.com
  port: 443
  ssl:  true
  accountName: ps-east-prod
  globalAccountName: ps-east-prod_3f0aff03-8206-480f-9b82-872c2d46f986
  accessKey: i7x6qm2k1rpg
  config:
    enabled: true

agent:
  simEnabled: true
  dockerEnabled: true
  includeMasters: true
  logLevel: info
  stdoutLogging: false
  proxyHost: ""
  proxyPort: ""
  proxyUser: ""
  proxyPass: ""
  metricsLimit: 4000
  hierarchyPath: "prod|gcp|"
  uniqueHostId: ""
  enableContainerAsHostID: false
  netviz: false
  netvizPort: 3892
  netvizImage:
    repository: docker.io/appdynamics/machine-agent-netviz
    tag: latest
    pullPolicy: Always

analytics:
  eventEndpoint: https://analytics.api.appdynamics.com
  port: 9090

serviceAccount:
  create: false
  name: appdynamics-infraviz

rbac:
  create: false
openshift:
  scc: false
